version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: mscroggs/bempp-cl-test:test
    steps:
      - checkout
      - run:
          command: |
            cd bempp-cl
            python3 setup.py install
          name: Install Bempp
      - run:
          command: python3 -m pytest --durations=50 notebooks/test_notebooks.py
          name: Run example notebooks


workflows:
  main:
    jobs:
      - build-and-test
