version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mscroggs/bempp-cl-test:latest
    steps:
      - checkout
      - run:
          command: |
              python3 -m flake8 bempp
              python3 -m flake8 test
          name: Run flake8 checks
      - run:
          command: python3 -m pydocstyle bempp/api
          name: Run pydocstyle checks
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
          command: python3 -m pytest test/simple
          name: Run Bempp simple tests
      - run:
          command: python3 -m pytest --durations=50 bempp
          name: Run Bempp unit tests
      - run:
          command: python3 -m pytest --durations=50 notebooks/test_notebooks.py
          name: Run example notebooks

workflows:
  main:
    jobs:
      - build-and-test
