version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  style-checks:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip3 install pydocstyle flake8
      - run:
          command: |
              python3 -m flake8 bempp
              python3 -m flake8 test
          name: Run flake8 checks
      - run:
          command: python3 -m pydocstyle bempp/api
          name: Run pydocstyle checks
    
  build-and-test-with-exafmm:
    docker:
      - image: mscroggs/bempp-cl-test:exafmm
    steps:
      - checkout
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
          command: python3 -m pytest test/simple
          name: Run Bempp simple tests
      - run:
          command: python3 -m pytest --durations=50 bempp
          name: Run Bempp unit tests
      - run:
          command: python3 -m pytest --durations=50 notebooks/test_notebooks.py
          name: Run example notebooks

workflows:
  main:
    jobs:
      - style-checks
      - build-and-test
