version: 2.1

jobs:
  large-tests:
    docker:
      - image: mscroggs/bempp-cl-test:latest
    steps:
      - checkout
      - run:
          command: python3 -m pytest --durations=10 test/validation
          name: Run Bempp validation tests
      - run:
          command: python3 -m pytest --durations=10 notebooks/test_notebooks.py
          name: Run example notebooks

workflows:
  main:
    jobs:
      - large-tests
# TODO: only run this on PR
# TODO: run benchmarks on push to master
