version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            sudo apt install python3-numpy python3-scipy python3-numba
            sudo apt install python3-pyopencl
            sudo apt install python-dolfin
            pip3 install meshio==3.2.12 pyqt5-sip==4.19.18 pyqtwebengine==5.12.1
          name: Install dependencies
      - run:
          command: pip3 install flake8 pytest
          name: Install flake8 and pytest
      - python/save-cache
#      - run:
#          command: python3 -m flake8 bempp --exclude=__init__.py
#          name: Flake8 checks
      - run:
          command: pip3 install . --user -v
          name: Install
      - run:
          command: python3 -m pytest bempp
          name: Run tests


workflows:
  main:
    jobs:
      - build-and-test
