version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip3 install flake8
          name: Install flake8
#      - run:
#          command: python3 -m flake8 bempp --exclude=__init__.py
#          name: Flake8 checks
      - run:
          command: |
            if [[ ! -d /home/circleci/miniconda ]]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh &&
                bash miniconda.sh -b -f -p /home/circleci/miniconda;
            else
                echo "Using cached miniconda";
            fi
            source ~/miniconda/bin/activate root
            conda env create -f environment.yml
            conda activate bempp
          name: Install miniconda and create bempp environment
      - run:
          command: |
            source ~/miniconda/bin/activate root
            conda activate bempp
            python3 -m pytest bempp
          name: Run tests


workflows:
  main:
    jobs:
      - build-and-test
