name: Release new version of Bempp-cl

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  update-website:
    name: Update bempp.com
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Install PyGitHub
      uses: pip3 install PyGitHub
    - name: Update website
      uses: python3 .github/scripts/update_website.py $BEMPPBOT_GITHUB_TOKEN
