on:
  push:
    branches:
      - master
      - staging

jobs:
  build-n-publish:
    name: Build and publish testing environment docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image with exafmm
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mscroggs/bempp-cl-test
          tags: exafmm, latest
          target: bempp-dev-env-with-exafmm
          cache_froms: mscroggs/bempp-cl-test:exafmm

      - name: Build and push Docker image with pyexafmm
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mscroggs/bempp-cl-test
          tags: pyexafmm
          target: bempp-dev-env-with-pyexafmm
          cache_froms: mscroggs/bempp-cl-test:pyexafmm
