on:
  push:
    branches:
      - master
      - docker

jobs:
  build-n-publish:
    name: Build and publish testing environment docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mscroggs/bempp-cl-test
