on:
  push:
    branches:
      - master

jobs:
  build-and-publish-docker:
    name: Build and publish testing environment docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mscroggs/bempp-cl-test
          tags: latest
          target: bempp-cl
          cache_froms: mscroggs/bempp-cl-test:latest
